config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'


  resources :restaurants, only: [:index, :new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
require 'net/http'
require 'uri'

class PagesController < ApplicationController
  def home
    @spotify_embed = get_spotify_oembed("https://open.spotify.com/track/4QreGo9Ivksjv4c3Bnk5f3")
    if params[:member]
      @members = @members.select { |member| member.start_with?(params[:member]) }
    end
  end

  def about
  end

  def contact
    @members = ["bob", "ana", "jack", "john"]


  end

  private

  def get_spotify_oembed(url)
    uri = URI("https://open.spotify.com/oembed")
    params = { :url => url }
    uri.query = URI.encode_www_form(params)

    response = Net::HTTP.get_response(uri)
    return JSON.parse(response.body)["html"] if response.is_a?(Net::HTTPSuccess)

    nil
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(strong_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def strong_params
    params.require(:restaurant).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSandbox2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

</head>

<body>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hello world!</h1>

app/views/pages/contact.html.erb
<h1>This is a contact page</h1>


<!-- app/views/pages/contact.html.erb -->
<form action="/contact" method="get">
  <input type="text"
  name="member"
  value="<%= params[:member] %>"
  placeholder="Who are you looking for?"
  >
  <input type="submit">
</form>

<% @members.each do |member| %>
<%= member %>
<% end %>


<% link_to "Go back home", root_path%>

app/views/pages/home.html.erb
<!---->
<p> <%= link_to "Contact page", contact_path %> </p>
<p> <%=  link_to "About page", about_path %> </p>
<br>
<!---->

<br>
<br>






<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/4QreGo9Ivksjv4c3Bnk5f3?utm_source=generator&theme=0" width="100%" height="272" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<br>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/0WfOuXw05LJq4ik1lVvTzi?utm_source=generato&theme=0" width="100%" height="272" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<br>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/4MTfvOrmGy9uiiPZrW55LY?utm_source=generator&theme=0" width="100%" height="272" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
<br>
<br>
<br>
<br>
<iframe width="100%" height="272" src="https://www.youtube.com/embed/s-hZseeHbCk" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br>
<br>
<iframe width="100%" height="272" scrolling="no" frameborder="no" style="filter: invert(1) hue-rotate(360deg);" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1351563160&color=%23282828&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=false"></iframe>
<br>
<br>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>


<%= link_to "Create a new one", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.rating %></p>


<%= link_to "Back to the list", restaurants_path %>